language: node_js
node_js:
  - "stable"

services:
  - docker

cache:
  directories:
    - "node_modules"

before_install:
  - npm -version

install:
  - npm install
  - docker build -t teste2epostgres/app .

after_install:
  - npm test:cov
  - docker-compose -f docker-compose.e2e.yml up --abort-on-container-exit --exit-code-from app
